# Generated by Django 4.1 on 2024-01-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
